root: true

plugins:
  - babel

env:
  browser: true
  jest: true
  node: true

extends:
  - airbnb-base

parser: "@babel/eslint-parser"

rules:
  no-console: 0
  import/extensions: 0
  "no-param-reassign": [2, { "props": false }]
